### ISSUE TITLE
Terraspace does not work for non-cloud providers

### ISSUE THREAD

**Issue by tckb** [boltops-tools/terraspace#131]
I  tested terraspace to use with `http` backend and it does not seem to support any other backend apart from aws/azure/gcp. I also tried the same with `local` backend. I end up having the same error.

## Checklist

- [x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    macOs/Intel/ 11.5 BigSur     |
| Terraform        |         v1.0.2 on darwin_amd64 |
| Terraspace       |       0.6.12  |
| Ruby             |     3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]    |

---

## Expected Behaviour

terraspace should work 

## Current Behavior

gives out the following error

```bash
[deployments] terraspace up test -y
<dir>/gems/terraspace-0.6.12/lib/terraspace/compiler/expander.rb:26:in `autodetect': undefined method `[]' for nil:NilClass (NoMethodError)
	from <dir>gems/memoist-0.16.2/lib/memoist.rb:213:in `autodetect'
	from <dir>/gems/terraspace-0.6.12/lib/terraspace/mod.rb:130:in `cache_dir'
...
````

## Step-by-step reproduction instructions
```
- terraspace new project deployments
- cd deployments
- terraspace new stack test
# update provider config in /deployments/config/terraform/backend.tf
# add local backend and remove aws plugin
- terrspace up test -y
```
## Code Sample

attaching the following project sample

[deployments.zip](https://github.com/boltops-tools/terraspace/files/6908283/deployments.zip)

**Comment by yisyang** [comment]
Was able to reproduce the issue today. @tckb captured the error perfectly. Something like a terraspace_plugin_http will be ideal for people who want to use a simple http terraform backend such as Gitlab.

## Setup

Setup project
```
terraspace new project terra
cd terra
terraspace new stack demo
# replace config/terraform/backend.tf
terraspace validate demo
```

backend.tf
```
terraform {
  backend "http" {
    address         = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV') %>"
    lock_address    = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV/lock') %>"
    unlock_address  = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV/lock') %>"
    username        = "<%= ENV["CI_USER"] %>"
    password        = "<%= ENV["CI_PAT"] %>"
  }
}
```

## Error
```
me@ubuntu2004:~/code/scott-machines/terra$ terraspace validate demo
Building .terraspace-cache/us-west-2/dev/stacks/demo
INFO: You're missing AWS credentials. Only local services are currently available
/home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/plugin/expander/friendly.rb:7:in `friendly_name': undefined method `to_sym' for nil:NilClass (NoMethodError)
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:93:in `block in plugins'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:87:in `each'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:87:in `plugins'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/layering.rb:11:in `main_layers'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/layering.rb:6:in `layers'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:62:in `full_layering'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:48:in `full_paths'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar/layer.rb:41:in `paths'
        from /home/yisyang/.gem/ruby/3.0.0/gems/memoist-0.16.2/lib/memoist.rb:169:in `paths'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar.rb:24:in `layer_paths'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/strategy/tfvar.rb:9:in `run'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/builder.rb:30:in `build_tfvars'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/builder.rb:13:in `build'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:57:in `build_root_module'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:52:in `build_unresolved'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:22:in `block in run'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/hooks/builder.rb:25:in `run_hooks'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/hooks/concern.rb:6:in `run_hooks'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:20:in `run'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/cli/commander.rb:9:in `run'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/cli.rb:229:in `validate'
        from /home/yisyang/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /home/yisyang/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/yisyang/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/command.rb:61:in `dispatch'
        from /home/yisyang/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /home/yisyang/.gem/ruby/3.0.0/gems/terraspace-0.6.19/exe/terraspace:14:in `<top (required)>'
        from /home/yisyang/.gem/ruby/3.0.0/bin/terraspace:25:in `load'
        from /home/yisyang/.gem/ruby/3.0.0/bin/terraspace:25:in `<main>'
```

## Alternate Error
**When NOT using `gem "terraspace_plugin_http"` in Gemfile**:
```
me@ubuntu2004:~/code/scott-machines/terra$ terraspace validate demo
/home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/expander.rb:26:in `autodetect': undefined method `[]' for nil:NilClass (NomethodError)
        from /home/me/.gem/ruby/3.0.0/gems/memoist-0.16.2/lib/memoist.rb:213:in `autodetect'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/mod.rb:130:in `cache_dir'
        from /home/me/.gem/ruby/3.0.0/gems/memoist-0.16.2/lib/memoist.rb:169:in `cache_dir'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/cleaner/backend_change.rb:34:in `current_backend'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/cleaner/backend_change.rb:20:in `purge?'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/cleaner/backend_change.rb:10:in `purge'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/cleaner.rb:16:in `backend_change_purge'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/compiler/cleaner.rb:9:in `clean'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:77:in `clean'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/builder.rb:13:in `run'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/cli/commander.rb:9:in `run'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/cli.rb:229:in `validate'
        from /home/me/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /home/me/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/me/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/lib/terraspace/command.rb:61:in `dispatch'
        from /home/me/.gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /home/me/.gem/ruby/3.0.0/gems/terraspace-0.6.19/exe/terraspace:14:in `<top (required)>'
        from /home/me/.gem/ruby/3.0.0/bin/terraspace:25:in `load'
        from /home/me/.gem/ruby/3.0.0/bin/terraspace:25:in `<main>'
```

## Nasty Workaround
Use http backend with gem "terraspace_plugin_aws" and have ~/.aws/credentials ready...
```
me@ubuntu2004:~/code/scott-machines/terra$ terraspace validate demo
Building .terraspace-cache/us-west-2/dev/stacks/demo
Built in .terraspace-cache/us-west-2/dev/stacks/demo
Current directory: .terraspace-cache/us-west-2/dev/stacks/demo
=> terraform init -get -input=false >> /tmp/terraspace/log/init/demo.log
2021/11/24 21:13:08 [DEBUG] GET https://gitlab.com/api/v4/projects/31586394/terraform/state/dev
=> terraform validate
Success! The configuration is valid.
```

**Comment by tongueroo** [comment]
Non-cloud support has been added in terraspace 0.7.0

Docs: https://terraspace.cloud/docs/learn/onprem/
