### ISSUE TITLE
Can't run the "demo" example on Mac

### ISSUE THREAD

**Issue by sharon-codefresh** [boltops-tools/terraspace#135]
I followed the "Getting Started" guide for AWS and installed Terraspace (0.6.13) using `brew`.
I was able to execute 
```
terraspace check_setup
Detected Terrspace version: 0.6.13
Detected Terraform bin: /usr/local/bin/terraform
Detected Terraform v1.0.4
Terraspace requires Terraform v0.12.x and above
You're all set!
```

And after that, I've executed
```
terraspace new project infra --plugin aws --examples
=> Creating new project called infra.
      create  infra
      create  infra/.gitignore
      create  infra/Gemfile
      create  infra/README.md
      create  infra/Terrafile
      create  infra/config/app.rb
       exist  infra
      create  infra/config/terraform/backend.tf
      create  infra/config/terraform/provider.tf
=> Creating test for new module: example
      create  infra/app/modules/example
      create  infra/app/modules/example/main.tf
      create  infra/app/modules/example/outputs.tf
      create  infra/app/modules/example/variables.tf
=> Creating new stack called demo.
      create  infra/app/stacks/demo
      create  infra/app/stacks/demo/main.tf
      create  infra/app/stacks/demo/outputs.tf
      create  infra/app/stacks/demo/variables.tf
=> Installing dependencies with: bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies.....
Fetching rake 13.0.6
Installing rake 13.0.6
Using concurrent-ruby 1.1.9
Using zeitwerk 2.4.2
Using public_suffix 4.0.6
Using aws-eventstream 1.1.1
Using jmespath 1.4.0
Using memoist 0.16.2
Using multipart-post 2.1.1
Using digest-crc 0.6.4
Using unf_ext 0.0.7.7
Using eventmachine 1.2.7
Using google-protobuf 3.17.3 (universal-darwin)
Using jwt 2.2.3
Using multi_json 1.15.0
Using os 1.1.1
Using httpclient 2.8.3
Using mini_mime 1.1.0
Using rainbow 3.0.0
Using uber 0.1.0
Using retriable 3.1.2
Fetching minitest 5.14.4
Using bundler 2.2.25
Using text-table 1.2.4
Using google-cloud-errors 1.1.0
Using graph 2.10.0
Using tilt 2.0.10
Using rspec-support 3.10.2
Using rubyzip 2.3.2
Using thor 1.1.0
Using tty-tree 0.4.0
Using i18n 1.8.10
Using tzinfo 2.0.4
Using addressable 2.8.0
Using aws-sigv4 1.2.4
Using gcp_data 0.2.0
Using diff-lcs 1.4.4
Using unf 0.1.4
Using eventmachine-tail 0.6.5
Using trailblazer-option 0.1.1
Using dsl_evaluator 0.1.3
Using rspec-core 3.10.1
Using rspec-expectations 3.10.1
Fetching racc 1.5.2
Using declarative 0.0.20
Using domain_name 0.5.20190701
Using representable 3.1.1
Using http-cookie 1.0.4
Using googleapis-common-protos-types 1.1.0
Fetching aws-partitions 1.489.0
Fetching faraday 0.17.4
Using timeliness 0.3.10
Fetching rexml 3.2.5
Using rspec-mocks 3.10.2
Using deep_merge 1.2.1
Using azure_info 0.1.2
Fetching webrick 1.7.0
Using grpc 1.38.0 (universal-darwin)
Using rspec 3.10.0
Using googleapis-common-protos 1.3.11
Using rhcl 0.1.0
Using grpc-google-iam-v1 0.6.11
Using hcl_parser 0.1.0
Installing aws-partitions 1.489.0
Installing minitest 5.14.4
Fetching aws-sdk-core 3.119.1
Installing faraday 0.17.4
Installing webrick 1.7.0
Installing rexml 3.2.5
Fetching activesupport 6.1.4.1
Installing racc 1.5.2 with native extensions
Using faraday-cookie_jar 0.0.7
Using ms_rest 0.7.6
Using signet 0.15.0
Using google-cloud-env 1.5.0
Using googleauth 0.17.0
Using google-cloud-core 1.6.0
Fetching faraday_middleware 0.14.0
Using google-apis-core 0.4.1
Using ms_rest_azure 0.12.0
Using google-apis-iamcredentials_v1 0.6.0
Using azure_mgmt_resources 0.18.2
Using azure_mgmt_storage 0.23.0
Using google-apis-storage_v1 0.6.0
Fetching gapic-common 0.3.4
Using google-cloud-storage 1.34.1
Installing aws-sdk-core 3.119.1
Installing activesupport 6.1.4.1
Installing faraday_middleware 0.14.0
Installing gapic-common 0.3.4
Using aws-sdk-dynamodb 1.62.0
Using aws-sdk-kms 1.46.0
Using aws-sdk-secretsmanager 1.48.0
Using aws-sdk-ssm 1.115.0
Using aws_data 0.1.1
Using cli-format 0.2.0
Using render_me_pretty 0.8.3
Using rspec-terraspace 0.3.0
Fetching google-cloud-secret_manager-v1beta1 0.8.0
Fetching google-cloud-secret_manager-v1 0.8.0
Fetching aws-sdk-s3 1.99.0
Fetching nokogiri 1.12.3 (x86_64-darwin)
Installing google-cloud-secret_manager-v1beta1 0.8.0
Installing google-cloud-secret_manager-v1 0.8.0
Using google-cloud-secret_manager 1.1.2
Using terraspace_plugin_google 0.3.0
Installing aws-sdk-s3 1.99.0
Using s3-secure 0.5.1
Using terraspace_plugin_aws 0.3.0
Installing nokogiri 1.12.3 (x86_64-darwin)
Using terraspace-bundler 0.4.0
Fetching azure-core 0.1.15
Installing azure-core 0.1.15
Fetching azure-storage-common 1.1.0
Installing azure-storage-common 1.1.0
Fetching azure-storage-blob 1.1.0
Installing azure-storage-blob 1.1.0
Using terraspace_plugin_azurerm 0.3.1
Using terraspace 0.6.13
Bundle complete! 3 Gemfile dependencies, 101 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
================================================================
Congrats! You have successfully created a terraspace project.
Check out the created files. Adjust to the examples and then deploy with:

    cd infra
    terraspace up demo -y   # to deploy
    terraspace down demo -y # to destroy

More info: https://terraspace.cloud/
```
note that as part of this execution it seems like some components have been installed but it finished successfully.

When I tried to launch the "demo" I receive the following error:
```
terraspace up demo
You have already activated faraday 1.7.0, but your Gemfile requires faraday 0.17.4. Prepending `bundle exec` to your command may solve this.
Traceback (most recent call last):
	9: from /opt/terraspace/embedded/bin/terraspace:23:in `<main>'
	8: from /opt/terraspace/embedded/bin/terraspace:23:in `load'
	7: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/exe/terraspace:11:in `<top (required)>'
	6: from /opt/terraspace/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	5: from /opt/terraspace/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	4: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace.rb:5:in `<top (required)>'
	3: from /opt/terraspace/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /opt/terraspace/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	1: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/autoloader.rb:3:in `<top (required)>'
/opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/autoloader.rb:3:in `require': cannot load such file -- zeitwerk (LoadError)
```

Note that now I receive the same error even for executing `terraspace check_setup`.

**Comment by sharon-codefresh** [comment]
I've installed another version of `ruby` (ruby 3.0.2) using `brew install ruby`.
Then I've executed:
```
gem install bundler:2.2.22
```

Although I'm able now to execute `terraspace check_setup"  by Prepending `bundle exec` to the `terraspace` command.
I get now another error:

```
bundle exec terraspace up demo

You can also get rid of this message by setting AWS_REGION or configuring ~/.aws/config with the region
Building .terraspace-cache/us-east-1/dev/stacks/demo
Traceback (most recent call last):
	25: from /opt/terraspace/embedded/bin/terraspace:23:in `<main>'
	24: from /opt/terraspace/embedded/bin/terraspace:23:in `load'
	23: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/exe/terraspace:14:in `<top (required)>'
	22: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	21: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/command.rb:61:in `dispatch'
	20: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	19: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	17: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/cli.rb:222:in `up'
	16: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/cli/up.rb:8:in `run'
	15: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/cli/up.rb:20:in `build'
	14: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/builder.rb:20:in `run'
	13: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/hooks/concern.rb:6:in `run_hooks'
	12: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/hooks/builder.rb:25:in `run_hooks'
	11: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/builder.rb:22:in `block in run'
	10: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/builder.rb:52:in `build_unresolved'
	 9: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/builder.rb:57:in `build_root_module'
	 8: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:11:in `build'
	 7: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:19:in `build_config'
	 6: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:40:in `build_config_terraform'
	 5: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:40:in `each'
	 4: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:43:in `block in build_config_terraform'
	 3: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:55:in `build_config_file'
	 2: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/builder.rb:60:in `build_mod_file'
	 1: from /opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/writer.rb:37:in `write'
/opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.13/lib/terraspace/compiler/writer.rb:37:in `write': Permission denied @ rb_sysopen - /Users/vendrov/Source/Terraspace/infra/.terraspace-cache/us-east-1/dev/stacks/demo/provider.tf (Errno::EACCES)
```

**Comment by tongueroo** [comment]
Bummer. Dug into this. Addressing this by improving the terraspace wrapper generated by the standalone installers. Details here: 

* https://terraspace.cloud/docs/install/standalone/details/#terraspace-wrapper  
* https://terraspace.cloud/docs/install/shim/

You won't have to type `bundle exec`. Believe this should resolve the issues. 🧐

In addition, added a friendly usage message with instructions on how to resolve if the error occurs. PR: https://github.com/boltops-tools/terraspace/pull/177  The standalone installer's new shim, as of terraspace 0.7.0 includes this smarter shim already.
