### ISSUE TITLE
Unable to retrieve secrets from Azure Key Vault after upgrade to Terraspace 0.7.0

### ISSUE THREAD

**Issue by dbodencnve** [boltops-tools/terraspace#184]
## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   Debian 10.11  |
| Terraform        |   1.1.2      |
| Terraspace       |  0.7.0       |
| Ruby             |   3.0.3p157      |

---

## Expected Behaviour

I am using the azure_secret helper to retrieve a secret from my Azure Key Vault.

## Current Behavior

Since the upgrade from Terraspace 0.6.23 to 0.7.0 I can no longer fetch secrets from Azure Key Vault.

## Step-by-step reproduction instructions

I defined the following in my tfvars file:

`license = "<%= azure_secret("fortigatevm-license") %>"`

When running terraspace init I am receiving the following stack trace:

```
21:52 # ts init fortigate-vm
Building .terraspace-cache/westeurope/dev/stacks/fortigate-vm
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/backend.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/provider.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/backend.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/provider.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/1-dev.auto.tfvars
Resource Group dev-westeurope already exists
Storage Account ts8afdwesteuropedev already exists
Storage Container terraform-state already exists
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/backend.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/provider.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/main.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/outputs.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-config/variables.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/backend.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/provider.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/main.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/outputs.tf
Created .terraspace-cache/westeurope/dev/stacks/fortigate-vm/variables.tf
ArgumentError: wrong number of arguments (given 2, expected 1)
Error evaluating ERB template around line 21 of: /workspaces/fortigatevm/ftgvm/app/stacks/fortigate-vm/tfvars/dev.tfvars:
19 bootstrap-fgtvm      = "fgtvm.conf"
20 
21 license = "<%= azure_secret("fortigatevm-license") %>"

Original backtrace (last 8 lines):
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace_plugin_azurerm-0.3.2/lib/terraspace_plugin_azurerm/interfaces/helper/secret/fetcher.rb:23:in `get_secret'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace_plugin_azurerm-0.3.2/lib/terraspace_plugin_azurerm/interfaces/helper/secret/fetcher.rb:20:in `fetch'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace_plugin_azurerm-0.3.2/lib/terraspace_plugin_azurerm/interfaces/helper/secret.rb:16:in `fetch'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace_plugin_azurerm-0.3.2/lib/terraspace_plugin_azurerm/interfaces/helper.rb:6:in `azure_secret'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace-0.6.23/lib/terraspace/plugin/helper/interface.rb:25:in `block in cache_helper'
/workspaces/fortigatevm/ftgvm/app/stacks/fortigate-vm/tfvars/dev.tfvars:21:in `__tilt_3140'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'

Re-run with FULL_BACKTRACE=1 to see all lines
```

**Comment by tongueroo** [comment]
Fixed by https://github.com/boltops-tools/terraspace_plugin_azurerm/pull/10
