### ISSUE TITLE
Enabled OIDC in terraspace_plugin_azurerm

### ISSUE THREAD

**Issue by ahmedulde7** [boltops-tools/terraspace#290]
terraform provider supports oidc but when we use this block in terraspace it give ARM Rest error

# We strongly recommend using the required_providers block to set the
# Azure Provider source and version being used
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.7.0"
    }
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  use_oidc = true
  features {}
}

Terraspace error:
Exception Armrest::Error: #<Net::HTTPUnauthorized:0x000055e98bb9da78>
/var/lib/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/api/base.rb:43:in `request'
/var/lib/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/api/base.rb:18:in `block (2 levels) in <class:Base>'
/var/lib/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/services/resource_group.rb:20:in `create_or_update'
var/lib/gems/3.0.0/gems/terraspace_plugin_azurerm-0.7.0/lib/terraspace_plugin_azurerm/interfaces/backend/resource_group_creator.rb:19:in `create_or_update_resource_group'

**Comment by teddimitrov** [comment]
Did you find a solution/workaround to this by any chance? Experiencing same behavior and error:

#297 

Building .terraspace-cache/eastus/dev/stacks/demo
Current directory: .terraspace-cache/eastus/dev/stacks/demo
Creating Resource Group dev-eastus...
Exception Armrest::Error: #<Net::HTTPUnauthorized:0x0000556a81945408>
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/api/base.rb:43:in `request'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/api/base.rb:18:in `block (2 levels) in <class:Base>'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/armrest-0.1.3/lib/armrest/services/resource_group.rb:20:in `create_or_update'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/terraspace_plugin_azurerm-0.7.0/lib/terraspace_plugin_azurerm/interfaces/backend/resource_group_creator.rb:19:in `create_or_update_resource_group'

**Comment by HoLengZai** [comment]
I think it's not the correct repo to put that issue, it should be in
[boltops-tools/armrest](https://github.com/boltops-tools/armrest.git)
I will try to fork that repo and implement OIDC provider on it as I don't want to handle any secret on my project.
it seems that for people said it works, they don't mention about the auto creation of the backend for the tfstate which is implemented by terraspace using terraspace_plugin_azurerm which used armrest gem
Hence I do believe that OIDC will need to be implemented in armrest
@tongueroo, let me know if I am wrong about it...

**Comment by HoLengZai** [comment]
@tongueroo 

Using AI, i success to implement a workable solution for using OIDC authentication provider... So terraspace can now create automatically the tfstate backend using azure federated workload identity.
I will continue some testing and i will be able to provide a PR

**Comment by HoLengZai** [comment]
@tongueroo 
I have created the pull request in the armrest repo [https://github.com/boltops-tools/armrest/pull/9](https://github.com/boltops-tools/armrest/pull/9)
Hence this issue can be closed if you approve the PR.
Thanks
