### ISSUE TITLE
`-no-color` fails in Terraspace 2.2.15 with opentofu 1.6

### ISSUE THREAD

**Issue by jrdemasi** [boltops-tools/terraspace#344]
## Checklist

- [X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |     Ubuntu    |
| Opentofu        |    1.6     |
| Terraspace       |     2.2.15    |
| Ruby             |     3.1    |

---

## Expected Behaviour
The plan should be written to a file, and output should not have color

## Current Behavior
There is an error indicating terraform isn't available, even though this is a system with opentofu 1.6.  It seems something about the -no-color option is forcing `terraform` instead of `tofu` to be used.  

## Step-by-step reproduction instructions

1. Run a plan with -no-color -out tfplan on a system with terraform
2. Run the same plan on a system with opentofu

## Code Sample

```
terraspace plan dashboards -no-color -out tfplan
Building .terraspace-cache~us-east-1/dev/stacks/dashboards
Exception Errno::ENOENT: No such file or directory - terraform
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:117:in ``'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:117:in `terraform_help'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:84:in `terraform_arg_types_for_command'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:64:in `terraform_arg_types'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:41:in `block in reconstruct_hash_args'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:40:in `each'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:40:in `reconstruct_hash_args'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:26:in `pass_args'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/args/pass.rb:13:in `args'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/runner.rb:22:in `args'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/runner.rb:15:in `block in run'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/runner.rb:97:in `time_took'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/terraform/runner.rb:14:in `run'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/init.rb:23:in `block in init'
/usr/local/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
/usr/local/lib/ruby/3.1.0/timeout.rb:36:in `block in catch'
/usr/local/lib/ruby/3.1.0/timeout.rb:36:in `catch'
/usr/local/lib/ruby/3.1.0/timeout.rb:36:in `catch'
/usr/local/lib/ruby/3.1.0/timeout.rb:123:in `timeout'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/init.rb:22:in `init'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/init.rb:12:in `run'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/commander.rb:10:in `run'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/plan.rb:43:in `plan_only'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/plan.rb:17:in `perform'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/plan.rb:11:in `run'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli.rb:165:in `plan'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/command.rb:76:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/terraspace-2.2.15/lib/terraspace/cli/concern.rb:65:in `start'
/usr/local/bundle/gems/terraspace-2.2.15/exe/terraspace:7:in `<top (required)>'
/usr/local/bundle/bin/terraspace:25:in `load'
/usr/local/bundle/bin/terraspace:25:in `<main>'
```

Without -no-color: 

```
terraspace plan dashboards -out dashboards.plan    

Building .terraspace-cache~us-east-1/dev/stacks/dashboards
Current directory: .terraspace-cache~us-east-1/dev/stacks/dashboards
=> tofu init -get -input=false >> /tmp/terraspace/log/init/dashboards.log
=> tofu plan -input=false -out dashboards.plan
Acquiring state lock. This may take a few moments...
<redacted>

OpenTofu used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
```
Works fine with terraform, doesn't work with opentofu

**Comment by jrdemasi** [comment]
If it's relevant, it seems when using outputs between stacks, state is also failing to pull because it's using `terraform state pull`

**Comment by jrdemasi** [comment]
I've got a PR in-progress for this and #338.  Getting it approved now by my company just so I can get credit for contributing to open source :-)
