### ISSUE TITLE
Creating a new project in Docker container fails

### ISSUE THREAD

**Issue by gs-scooter** [boltops-tools/terraspace#346]
Steps:

Ran the following Docker command per [instructions](https://terraspace.cloud/docs/install/docker/aws/):
`docker run --rm -ti -v $HOME/.aws:/root/.aws ghcr.io/boltops-tools/terraspace`

Attempted to create new project in container per instructions on same page:
`terraspace new project infra --examples`

This results in an error. See log below:
```
root@dc34a6ef4b9f:~# terraspace new project infra --examples
=> Creating new project called infra
       exist  infra
   identical  infra/.gitignore
   identical  infra/Gemfile
   identical  infra/README.md
   identical  infra/Terrafile
   identical  infra/config/app.rb
=> Installing dependencies with: bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Installing bigdecimal 3.1.5 with native extensions
Installing racc 1.7.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bigdecimal-3.1.5/ext/bigdecimal
/opt/terraspace/embedded/bin/ruby -I /opt/terraspace/embedded/lib/ruby/3.0.0 -r ./siteconf20240112-108-269bq4.rb
extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/terraspace/embedded/bin/$(RUBY_BASE_NAME)
/opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:482:in `try_do': The compiler failed to generate an executable file.
(RuntimeError)
You have to install development tools first.
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:608:in `block in try_compile'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:557:in `with_werror'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:608:in `try_compile'
        from extconf.rb:6:in `block in have_builtin_func'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:982:in `block in checking_for'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:981:in `checking_for'
        from extconf.rb:5:in `have_builtin_func'
        from extconf.rb:18:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bigdecimal-3.1.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bigdecimal-3.1.5 for inspection.
Results logged to
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bigdecimal-3.1.5/gem_make.out

  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /opt/terraspace/embedded/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/installer.rb:845:in `build_extensions'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/source/rubygems.rb:203:in `install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:54:in
`install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:130:in
`do_install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:121:in
`block in worker_pool'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:62:in `apply_func'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:57:in `block in process_queue'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:54:in `loop'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:54:in `process_queue'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:90:in `block (2 levels) in
create_threads'

An error occurred while installing bigdecimal (3.1.5), and Bundler cannot continue.

In Gemfile:
  terraspace_plugin_aws was resolved to 0.6.1, which depends on
    s3-secure was resolved to 0.7.0, which depends on
      cli-format was resolved to 0.5.0, which depends on
        activesupport was resolved to 7.1.2, which depends on
          bigdecimal
LoadError: cannot load such file -- terraspace_plugin_aws
ERROR: Unable to require plugin terraspace_plugin_aws
Are you sure you the plugin exists and you specified the right plugin option.
You specified --plugin aws
```

**Comment by tongueroo** [comment]
For posterity https://github.com/boltops-tools/terraspace-dockerfiles

**Comment by FloGerber** [comment]
I have the same Error, but it seems to be only happening for the Ubuntu/Debian Package from apt and if there is any plugin specified.

**official Alpine Image:**
```
sudo docker run --rm -ti ghcr.io/boltops-tools/terraspace:alpine
Unable to find image 'ghcr.io/boltops-tools/terraspace:alpine' locally
alpine: Pulling from boltops-tools/terraspace
df9b9388f04a: Pull complete 
837e9cfc7e43: Pull complete 
c7850f1a8c23: Pull complete 
3f2622d3c4c5: Pull complete 
7e0fef0f423d: Pull complete 
acc542de96b9: Pull complete 
9f64da7c7cef: Pull complete 
63a9c1ea09ee: Pull complete 
Digest: sha256:115a72611918b448f54d3ca1a85f80b1d41da4ff3dee25dca606c28cf573376c
Status: Downloaded newer image for ghcr.io/boltops-tools/terraspace:alpine
/tmp # terraspace new project init --plugin azurerm --no-examples
=> Creating new project called init
      create  init
      create  init/.gitignore
      create  init/Gemfile
      create  init/README.md
      create  init/Terrafile
      create  init/config/app.rb
=> Installing dependencies with: bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will
break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching logger 1.7.0
Fetching minitest 5.25.5
Fetching securerandom 0.3.2
Fetching benchmark 0.4.0
Fetching connection_pool 2.5.3
Fetching mutex_m 0.3.0
Fetching azure_info 0.1.5
Fetching hashie 5.0.0
Fetching base64 0.2.0
Fetching bigdecimal 3.1.9
Fetching drb 2.2.1
Fetching concurrent-ruby 1.3.5
Installing securerandom 0.3.2
Installing logger 1.7.0
Installing connection_pool 2.5.3
Installing azure_info 0.1.5
Installing benchmark 0.4.0
Installing mutex_m 0.3.0
Using memoist 0.16.2
Using rainbow 3.1.1
Fetching thor 1.3.2
Fetching rack 3.1.14
Fetching zeitwerk 2.6.18
Installing base64 0.2.0
Installing drb 2.2.1
Installing minitest 5.25.5
Fetching aws-eventstream 1.3.2
Fetching aws-partitions 1.1103.0
Installing hashie 5.0.0
Installing thor 1.3.2
Installing zeitwerk 2.6.18
Using jmespath 1.6.2
Using bundler 2.2.32
Using text-table 1.2.4
Using deep_merge 1.2.2
Installing aws-eventstream 1.3.2
Installing bigdecimal 3.1.9 with native extensions
Fetching diff-lcs 1.6.2
Fetching dotenv 3.1.8
Installing rack 3.1.14
Installing aws-partitions 1.1103.0
Installing dotenv 3.1.8
Using eventmachine 1.2.7
Fetching graph 2.11.1
Installing diff-lcs 1.6.2
Fetching racc 1.8.1
Installing concurrent-ruby 1.3.5
Fetching tilt 2.6.0
Fetching rexml 3.4.1
Fetching rspec-support 3.13.3
Fetching rubyzip 2.4.1
Installing racc 1.8.1 with native extensions
Installing tilt 2.6.0
Using tty-tree 0.4.0
Using rhcl 0.1.0
Fetching aws-sigv4 1.11.0
Using eventmachine-tail 0.6.5
Using hcl_parser 0.2.2
Installing rspec-support 3.13.3
Fetching rspec-expectations 3.13.4
Fetching rspec-mocks 3.13.4
Fetching rspec-core 3.13.3
Installing aws-sigv4 1.11.0
Installing rubyzip 2.4.1
Installing rexml 3.4.1
Installing rspec-mocks 3.13.4
Installing rspec-expectations 3.13.4
Fetching aws-sdk-core 3.224.0
Using tzinfo 2.0.6
Fetching i18n 1.14.7
Installing rspec-core 3.13.3
Installing i18n 1.14.7
Using zip_folder 0.1.0
Installing graph 2.11.1
Installing aws-sdk-core 3.224.0
Fetching rspec 3.13.0
Installing rspec 3.13.0
Fetching nokogiri 1.17.2 (x86_64-linux)
Fetching aws-sdk-kms 1.101.0
Installing aws-sdk-kms 1.101.0
Fetching aws-sdk-s3 1.186.0
Installing aws-sdk-s3 1.186.0
Installing nokogiri 1.17.2 (x86_64-linux)
Fetching activesupport 7.1.5.1
Installing activesupport 7.1.5.1
Fetching armrest 0.2.2
Fetching dsl_evaluator 0.3.2
Fetching rspec-terraspace 0.3.3
Fetching cli-format 0.6.1
Fetching render_me_pretty 1.0.0
Installing armrest 0.2.2
Installing dsl_evaluator 0.3.2
Installing cli-format 0.6.1
Installing rspec-terraspace 0.3.3
Using terraspace-bundler 0.5.0
Fetching terraspace_plugin_azurerm 0.7.1
Installing terraspace_plugin_azurerm 0.7.1
Installing render_me_pretty 1.0.0
Fetching terraspace 2.2.17
Installing terraspace 2.2.17
Bundle complete! 3 Gemfile dependencies, 57 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * `Zip::File`
  * `Zip::Entry`
  * `Zip::InputStream`
  * `Zip::OutputStream`
  * `Zip::DOSTime`

Run your test suite with the `RUBYZIP_V3_API_WARN` environment
variable set to see warnings about usage of the old API. This will
help you to identify any changes that you need to make to your code.
See https://github.com/rubyzip/rubyzip/wiki/Updating-to-version-3.x for
more information.

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
       exist  init
      create  init/config/terraform/backend.tf
      create  init/config/terraform/provider.tf
      create  init/app/modules
      create  init/app/stacks
================================================================
Congrats! You have successfully created a terraspace project.
Check out the created files.

    cd init

You can create starter modules and stacks with their generators:

    terraspace new module example
    terraspace new stack demo

Add your code to them, and deploy when you are ready:

    terraspace up demo -y   # to deploy

Destroy with:

    terraspace down demo -y # to destroy

More info: https://terraspace.cloud/
```

**Official Ubuntu Image:**

```
docker run --rm -ti ghcr.io/boltops-tools/terraspace
Unable to find image 'ghcr.io/boltops-tools/terraspace:latest' locally
latest: Pulling from boltops-tools/terraspace
43f89b94cd7d: Pull complete 
bf8bc7debcc6: Pull complete 
48e5cfa108c3: Pull complete 
46dc41b8b4e4: Pull complete 
3fc1898163d0: Pull complete 
d5e04d253fc4: Pull complete 
5d25f81739eb: Pull complete 
7136cfa5bd27: Pull complete 
f3ef9497eef9: Pull complete 
41cff24df0ea: Pull complete 
30fcaf6137a9: Pull complete 
b37da3a2a3a4: Pull complete 
Digest: sha256:71fcb8dc2fe94aa05e5baab676af070320eded458a8ddb4cfa5cd7c3664b9a4f
Status: Downloaded newer image for ghcr.io/boltops-tools/terraspace:latest
root@706a6fefb062:~# terraspace new project init --plugin azurerm --no-examples
=> Creating new project called init
      create  init
      create  init/.gitignore
      create  init/Gemfile
      create  init/README.md
      create  init/Terrafile
      create  init/config/app.rb
=> Installing dependencies with: bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on
this machine.
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching base64 0.2.0
Fetching benchmark 0.4.0
Fetching drb 2.2.1
Fetching concurrent-ruby 1.3.5
Fetching bigdecimal 3.1.9
Fetching connection_pool 2.5.3
Fetching minitest 5.25.5
Fetching logger 1.7.0
Fetching securerandom 0.3.2
Fetching azure_info 0.1.5
Fetching mutex_m 0.3.0
Fetching hashie 5.0.0
Installing base64 0.2.0
Installing connection_pool 2.5.3
Installing benchmark 0.4.0
Installing drb 2.2.1
Fetching rack 3.1.14
Installing bigdecimal 3.1.9 with native extensions
Fetching thor 1.3.2
Installing azure_info 0.1.5
Installing securerandom 0.3.2
Installing logger 1.7.0
Fetching zeitwerk 2.6.18
Fetching aws-eventstream 1.3.2
Installing mutex_m 0.3.0
Fetching aws-partitions 1.1103.0
Installing minitest 5.25.5
Fetching diff-lcs 1.6.2
Fetching dotenv 3.1.8
Fetching graph 2.11.1
Installing hashie 5.0.0
Installing aws-eventstream 1.3.2
Installing zeitwerk 2.6.18
Installing aws-partitions 1.1103.0
Fetching racc 1.8.1
Installing dotenv 3.1.8
Installing rack 3.1.14
Fetching tilt 2.6.0
Installing concurrent-ruby 1.3.5
Fetching rexml 3.4.1
Installing diff-lcs 1.6.2
Fetching rspec-support 3.13.3
Fetching rubyzip 2.4.1
Fetching aws-sigv4 1.11.0
Installing racc 1.8.1 with native extensions
Installing rexml 3.4.1
Installing rspec-support 3.13.3
Installing aws-sigv4 1.11.0
Installing rubyzip 2.4.1
Installing graph 2.11.1
Installing tilt 2.6.0
Installing thor 1.3.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bigdecimal-3.1.9/ext/bigdecimal
/opt/terraspace/embedded/bin/ruby -I /opt/terraspace/embedded/lib/ruby/3.0.0 -r ./siteconf20250514-15-gg2hyy.rb
extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/terraspace/embedded/bin/$(RUBY_BASE_NAME)
/opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:482:in `try_do': The compiler failed to generate an executable
file. (RuntimeError)
You have to install development tools first.
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:608:in `block in try_compile'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:557:in `with_werror'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:608:in `try_compile'
        from extconf.rb:6:in `block in have_builtin_func'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:982:in `block in checking_for'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
        from /opt/terraspace/embedded/lib/ruby/3.0.0/mkmf.rb:981:in `checking_for'
        from extconf.rb:5:in `have_builtin_func'
        from extconf.rb:18:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bigdecimal-3.1.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bigdecimal-3.1.9 for
inspection.
Results logged to
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bigdecimal-3.1.9/gem_make.out

  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /opt/terraspace/embedded/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /opt/terraspace/embedded/lib/ruby/3.0.0/rubygems/installer.rb:845:in `build_extensions'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/source/rubygems.rb:203:in
`install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:54:in
`install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:130:in
`do_install'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:121:in
`block in worker_pool'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:62:in `apply_func'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:57:in `block in
process_queue'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:54:in `loop'
  /opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:54:in `process_queue'
/opt/terraspace/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/worker.rb:90:in `block (2 levels)
in create_threads'

An error occurred while installing bigdecimal (3.1.9), and Bundler cannot continue.

In Gemfile:
  terraspace_plugin_azurerm was resolved to 0.7.1, which depends on
    armrest was resolved to 0.2.2, which depends on
      activesupport was resolved to 7.1.5.1, which depends on
        bigdecimal
LoadError: cannot load such file -- terraspace_plugin_azurerm
ERROR: Unable to require plugin terraspace_plugin_azurerm
Are you sure you the plugin exists and you specified the right plugin option.
You specified --plugin azurerm
```

As a workaround, installing the .deb package seems to be working.

```
wget https://apt.boltops.com/packages/terraspace/terraspace-latest.deb
dpkg -i terraspace-latest.deb
```
